# Generated by Django 3.2 on 2021-04-30 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_word', models.CharField(max_length=100)),
                ('rus_word', models.CharField(max_length=100)),
                ('transcription_uk', models.CharField(max_length=100)),
                ('transcription_us', models.CharField(max_length=100)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemorizingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemorizingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completes', models.IntegerField()),
                ('fails', models.IntegerField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorizer.memorizinglist')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorizer.word')),
            ],
        ),
    ]
