# Generated by Django 3.2 on 2021-05-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorizer', '0003_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='failed',
            field=models.IntegerField(default=0),
        ),
    ]
