# Generated by Django 3.2 on 2021-05-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorizer', '0005_remove_statistics_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
