# Generated by Django 3.2 on 2021-05-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorizer', '0006_statistics_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='user_text',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
